### ISSUE TITLE
Browser compatibility message breaks bookmark link

### ISSUE THREAD

**Issue by pautri** [clarin-eric/component-registry-front-end#169]
When using a bookmark link in an "unsupported" browser, the warning message interferes with the bookmark functionality, i.e. the target profile is not selected. Given that you don't know which browser people will use when sending them a link, it would be nice if they could just ignore the warning and go ahead looking at the profile.

**Comment by twagoo** [comment]
Note: to replicate, use Safari ≥ 16.6 (see #168)
