### ISSUE TITLE
Missing description in box for linked components in editor

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/component-registry-front-end#90]
Reported by Florian Schiel:

>When working with that interface it used to be very helpful that each component contained within a profile or within another component (blue boxes) when opened showed the content of the <Header>/<Description> element of the component. In the new Interface this Description is not shown; you have to switch from 'profiles' to 'components' and search for this specific component to see the description. If you have a profile with many components, this is very cumbersome.
>
>Could you add the element <Header>/<Description> to the display of a component within a profile?

**Comment by florianschiel** [comment]
Thanks for opening this issue for me.

**Comment by twagoo** [comment]
Fixed in `develop` as of 1bcb0b4.

![screen shot 2016-11-16 at 09 41 57](https://cloud.githubusercontent.com/assets/7011396/20340243/f42fc4ac-abe0-11e6-874f-207d2d0b5df7.png)
